#pragma once
#include "MainMapBlueprintBuilder.h"
#include "Map/GameMainMap/GameMainMapLibrary.h"
#include "Map/GameMainMap/GameMainMapPlayerController.h"
#include "Map/BaseMap/BaseMapWidget.h"
#include "Map/BaseMap/BaseSandboxMap.h"
#include "Map/BaseMap/SceneUI/OperationsCommandRoom/OperationsCommandRoomWidget.h"
#include "GridStrategyMapSystem/Display3D/GSMTile3D.h"
#include "SMS_SceneLibrary.h"
#include "BlueprintGameplayTagLibrary.h"
#include "FCS_FreeCameraPawn.h"
#include "Kismet/GameplayStatics.h"
#include "K2Node_CallParentFunction.h"
#include "K2Node_EnhancedInputAction.h"
#include "InputAction.h"
#include "InputMappingContext.h"
#include "InputModifiers.h"

namespace MainMapPointerMigration
{
using namespace MainMapBP;
inline const TMap<FName, FName> Renames = {
    {TEXT("BeginCommandMapPointer"),TEXT("CommandMap_BeginPointer")}, {TEXT("UpdateCommandMapPointer"),TEXT("CommandMap_UpdatePointer")},
    {TEXT("ReleaseCommandMapPointer"),TEXT("CommandMap_ReleasePointer")}, {TEXT("CancelCommandMapPointer"),TEXT("CommandMap_CancelPointer")},
    {TEXT("QueryCommandMapPointer"),TEXT("CommandMap_QueryPointer")}};

inline void ConvertOverrides(UBlueprint* BP)
{
    TMap<UK2Node_FunctionResult*, FString> ReturnDefaults;
    for (const auto& Pair : Renames)
    {
        auto* G = Find(BP, Pair.Key); if (!G) continue;
        G->Rename(*Pair.Value.ToString(), BP, REN_DontCreateRedirectors);
        const auto Nodes = G->Nodes;
        for (UEdGraphNode* N : Nodes)
        {
            if (N->IsA<UK2Node_CallParentFunction>()) { N->BreakAllNodeLinks(); G->RemoveNode(N); continue; }
            if (auto* E = Cast<UK2Node_FunctionEntry>(N))
            { E->FunctionReference.SetSelfMember(Pair.Value); E->SetExtraFlags(FUNC_Public | FUNC_BlueprintCallable); E->bIsEditable = true; E->ReconstructNode(); }
            if (auto* R = Cast<UK2Node_FunctionResult>(N))
            {
                R->FunctionReference.SetSelfMember(Pair.Value); R->bIsEditable = true;
                if (auto* ReturnPin = R->FindPin(TEXT("ReturnValue")))
                {
                    ReturnDefaults.Add(R, ReturnPin->DefaultValue);
                    auto Info = MakeShared<FUserPinInfo>(); Info->PinName = ReturnPin->PinName; Info->PinType = ReturnPin->PinType;
                    Info->DesiredPinDirection = EGPD_Input; Info->PinDefaultValue = ReturnPin->DefaultValue; R->UserDefinedPins.Add(Info);
                }
                R->ReconstructNode();
            }
        }
    }
    FBlueprintEditorUtils::MarkBlueprintAsStructurallyModified(BP);
    for (const auto& Pair : ReturnDefaults)
    {
        auto* Pin = P(Pair.Key,TEXT("ReturnValue"));
        S()->SetPinAutogeneratedDefaultValueBasedOnType(Pin);
        D(Pair.Key,TEXT("ReturnValue"),Pair.Value);
    }
    TArray<UEdGraph*> Graphs; BP->GetAllGraphs(Graphs);
    for (auto* G : Graphs) for (UEdGraphNode* N : G->Nodes) if (auto* Call = Cast<UK2Node_CallFunction>(N))
        if (const auto* NewName = Renames.Find(Call->FunctionReference.GetMemberName()))
        { Call->FunctionReference.SetSelfMember(*NewName); Call->ReconstructNode(); }
}
inline UK2Node_Event* Event(FGraph& G, FName Name, UClass* Owner)
{
    for (UEdGraph* Page : G.BP->UbergraphPages) for (UEdGraphNode* N : Page->Nodes)
        if (auto* E = Cast<UK2Node_Event>(N); E && E->EventReference.GetMemberName() == Name) return E;
    return G.Node<UK2Node_Event>([&](auto* E) { E->EventReference.SetExternalMember(Name, Owner); E->bOverrideFunction = true; });
}
inline void Append(FGraph& G, UEdGraphPin* Out, UEdGraphPin* NewFlow)
{
    const auto Old = Out->LinkedTo; Out->BreakAllPinLinks();
    auto* Seq = G.Sequence(Out); Link(Seq->GetThenPinGivenIndex(0), NewFlow);
    for (auto* Pin : Old) Link(Seq->GetThenPinGivenIndex(1), Pin);
}
inline bool Build(UBlueprint* BP, UInputAction* Wheel)
{
    Var(BP,TEXT("CommandMapMiddleMap"),Obj(ABaseSandboxMap::StaticClass()),TEXT("None"),TEXT("中键拖拽沙盘"));
    Var(BP,TEXT("CommandMapFoundMap"),Obj(ABaseSandboxMap::StaticClass()),TEXT("None"),TEXT("本次查询命中沙盘"));
    Var(BP,TEXT("CommandMapFoundWorld"),Struct(TBaseStructure<FVector>::Get()),TEXT(""),TEXT("本次查询命中位置"));
    Var(BP,TEXT("CommandMapBestDistance"),Real(),TEXT("0"),TEXT("本次查询最近距离"));
    Var(BP,TEXT("CommandMapRoomInputEnabled"),Bool(),TEXT("false"),TEXT("指挥室输入已激活"));
    Var(BP,TEXT("CommandMapPreviousClickEvents"),Bool(),TEXT("true"),TEXT("原始Actor点击开关"));
    Var(BP,TEXT("CommandMapEndingPlay"),Bool(),TEXT("false"),TEXT("控制器正在退出"));
    const TArray<FParam> BoolResult = {{TEXT("ReturnValue"),Bool(),TEXT("false")}};
    Declare(BP,TEXT("CommandMap_IsInRoom"),{},BoolResult);
    Declare(BP,TEXT("CommandMap_IsRoomReady"),{},BoolResult);
    Declare(BP,TEXT("CommandMap_OverPanel"),{},BoolResult);
    Declare(BP,TEXT("CommandMap_FindSandbox"),{},{{TEXT("OutMap"),Obj(ABaseSandboxMap::StaticClass()),TEXT("None")},{TEXT("OutWorldHit"),Struct(TBaseStructure<FVector>::Get()),TEXT("")},{TEXT("ReturnValue"),Bool(),TEXT("false")}});
    Declare(BP,TEXT("CommandMap_QueryPointer"),{{TEXT("bResolveTile"),Bool(),TEXT("true")}},{{TEXT("OutMap"),Obj(ABaseSandboxMap::StaticClass()),TEXT("None")},{TEXT("OutTile"),Obj(AGSMTile3D::StaticClass()),TEXT("None")},{TEXT("OutWorldHit"),Struct(TBaseStructure<FVector>::Get()),TEXT("")},{TEXT("OutScreenPosition"),Struct(TBaseStructure<FVector2D>::Get()),TEXT("")},{TEXT("ReturnValue"),Bool(),TEXT("false")}});
    Declare(BP,TEXT("CommandMap_SetRoomInput"),{{TEXT("Enabled"),Bool(),TEXT("false")}});
    Declare(BP,TEXT("CommandMap_BeginMiddle"),{},BoolResult);
    Declare(BP,TEXT("CommandMap_EndMiddle")); Declare(BP,TEXT("CommandMap_CancelAll")); Declare(BP,TEXT("CommandMap_Tick"));
    Declare(BP,TEXT("CommandMap_Zoom"),{{TEXT("Delta"),Real(),TEXT("0")}});
    if (!Compile(BP)) return false;
    ConvertOverrides(BP);
    if (!Compile(BP)) return false;
    const auto MapCall = [](FGraph& G, FName Name, UEdGraphPin* Map)
    { auto* N = G.Call(AGSMMap3D::StaticClass(),Name); Link(Map,P(N,TEXT("self"))); if (N->FindPin(TEXT("PlayerController"))) Link(G.Self(),P(N,TEXT("PlayerController"))); return N; };
    {
        FGraph G(BP,TEXT("CommandMap_IsInRoom")); auto* Tag = G.Call(USMS_SceneLibrary::StaticClass(),TEXT("GetCurrentSceneTag"));
        auto* Equal = G.Call(UBlueprintGameplayTagLibrary::StaticClass(),TEXT("EqualEqual_GameplayTag")); Link(Tag->GetReturnValuePin(),P(Equal,TEXT("A"))); D(Equal,TEXT("B"),TEXT("(TagName=\"GameScene.OperationsCommandRoom\")"));
        G.Return(G.Start(),{{TEXT("ReturnValue"),Equal->GetReturnValuePin()}});
    }
    {
        FGraph G(BP,TEXT("CommandMap_OverPanel")); auto* Guard = G.Branch(G.Start(),G.Valid(G.Get(TEXT("BaseWidget"))));
        auto* Current = G.Call(UBaseMapWidget::StaticClass(),TEXT("GetCurrentSceneUI")); Link(G.Get(TEXT("BaseWidget")),P(Current,TEXT("self")));
        auto* Cast = G.CastTo(UOperationsCommandRoomWidget::StaticClass(),Current->GetReturnValuePin(),Guard->GetThenPin());
        auto* Panel = G.Call(UOperationsCommandRoomWidget::StaticClass(),TEXT("IsPointerOverCommandPanel")); Link(Cast->GetCastResultPin(),P(Panel,TEXT("self")));
        G.Return(Cast->GetValidCastPin(),{{TEXT("ReturnValue"),Panel->GetReturnValuePin()}}); G.Return(Guard->GetElsePin()); G.Return(Cast->GetInvalidCastPin());
    }
    {
        FGraph G(BP,TEXT("CommandMap_IsRoomReady")); auto* InRoom = G.Call(TEXT("CommandMap_IsInRoom"));
        auto* Guard = G.Branch(G.Exec(G.Start(),InRoom),G.Both(InRoom->GetReturnValuePin(),G.Valid(G.Get(TEXT("BaseWidget")))));
        auto* Current = G.Call(UBaseMapWidget::StaticClass(),TEXT("GetCurrentSceneUI")); Link(G.Get(TEXT("BaseWidget")),P(Current,TEXT("self")));
        auto* Cast = G.CastTo(UOperationsCommandRoomWidget::StaticClass(),Current->GetReturnValuePin(),Guard->GetThenPin());
        auto* Loaded = G.Call(UBaseSceneWidget::StaticClass(),TEXT("IsSceneUILoaded")); Link(Cast->GetCastResultPin(),P(Loaded,TEXT("self")));
        auto* Enabled = G.Call(UWidget::StaticClass(),TEXT("GetIsEnabled")); Link(Cast->GetCastResultPin(),P(Enabled,TEXT("self")));
        auto* Transition = G.Call(USMS_SceneLibrary::StaticClass(),TEXT("GetTransitionState"));
        auto* Idle = G.Math(TEXT("EqualEqual_ByteByte"),Transition->GetReturnValuePin(),nullptr,TEXT("0"));
        G.Return(Cast->GetValidCastPin(),{{TEXT("ReturnValue"),G.Both(Idle,G.Both(Loaded->GetReturnValuePin(),Enabled->GetReturnValuePin()))}});
        G.Return(Guard->GetElsePin()); G.Return(Cast->GetInvalidCastPin());
    }
    {
        FGraph G(BP,TEXT("CommandMap_FindSandbox"));
        auto* Flow = G.Set(G.Start(),TEXT("CommandMapFoundMap"),TEXT("None")); Flow = G.Set(Flow,TEXT("CommandMapBestDistance"),TEXT("1.0e30"));
        auto* Type = G.Call(UGameMainMapLibrary::StaticClass(),TEXT("GetCurrentMapType"));
        auto* Panel = G.Call(TEXT("CommandMap_OverPanel")); Flow = G.Exec(Flow,Panel);
        auto* Local = G.Call(AController::StaticClass(),TEXT("IsLocalController"));
        auto* Guard = G.Branch(Flow,G.Both(G.Both(Local->GetReturnValuePin(),G.Not(Panel->GetReturnValuePin())),G.Math(TEXT("EqualEqual_ByteByte"),Type->GetReturnValuePin(),nullptr,TEXT("1"))));
        G.Return(Guard->GetElsePin());
        auto* InRoom = G.Call(TEXT("CommandMap_IsInRoom")); Flow = G.Exec(Guard->GetThenPin(),InRoom);
        auto* Ready = G.Call(TEXT("CommandMap_IsRoomReady")); Flow = G.Exec(Flow,Ready);
        auto* RoomAllowed = G.Branch(Flow,G.Math(TEXT("BooleanOR"),G.Not(InRoom->GetReturnValuePin()),Ready->GetReturnValuePin())); G.Return(RoomAllowed->GetElsePin());
        auto* Ray = G.Call(APlayerController::StaticClass(),TEXT("DeprojectMousePositionToWorld"));
        auto* RayOK = G.Branch(G.Exec(RoomAllowed->GetThenPin(),Ray),Ray->GetReturnValuePin()); G.Return(RayOK->GetElsePin());
        auto* Hit = G.Call(APlayerController::StaticClass(),TEXT("GetHitResultUnderCursorByChannel")); D(Hit,TEXT("TraceChannel"),TEXT("TraceTypeQuery1")); D(Hit,TEXT("bTraceComplex"),TEXT("true"));
        Flow = G.Exec(RayOK->GetThenPin(),Hit);
        auto* BreakHit = G.Call(UGameplayStatics::StaticClass(),TEXT("BreakHitResult")); Link(P(Hit,TEXT("HitResult")),P(BreakHit,TEXT("Hit")));
        auto* Actors = G.Call(UGameplayStatics::StaticClass(),TEXT("GetAllActorsOfClass")); P(Actors,TEXT("ActorClass"))->DefaultObject = ABaseSandboxMap::StaticClass(); Actors->ReconstructNode();
        auto* Loop = G.Loop(G.Exec(Flow,Actors),P(Actors,TEXT("OutActors")));
        auto* Cast = G.CastTo(ABaseSandboxMap::StaticClass(),P(Loop,TEXT("Array Element")),P(Loop,TEXT("LoopBody")));
        auto* Map = Cast->GetCastResultPin();
        auto* Data = MapCall(G,TEXT("GetMapData"),Map);
        auto* Allowed = G.Branch(Cast->GetValidCastPin(),G.Both(G.Both(G.Get(TEXT("bEnableSandboxMouseNavigation"),ABaseSandboxMap::StaticClass(),Map),G.Not(G.Get(TEXT("bHidden"),AActor::StaticClass(),Map))),G.Valid(Data->GetReturnValuePin())));
        auto* Groove = MapCall(G,TEXT("GetMouseHitOnMapGroove"),Map);
        auto* Inside = G.Branch(G.Exec(Allowed->GetThenPin(),Groove),Groove->GetReturnValuePin());
        // In a focused room architectural geometry can cover the table. Elsewhere require an actual visible hit.
        auto* RoomBranch = G.Branch(Inside->GetThenPin(),InRoom->GetReturnValuePin());
        auto* HitValid = G.Branch(RoomBranch->GetElsePin(),G.Valid(P(BreakHit,TEXT("HitActor"))));
        auto* Owner = G.Call(AActor::StaticClass(),TEXT("GetOwner")); Link(P(BreakHit,TEXT("HitActor")),P(Owner,TEXT("self")));
        auto* VisibleMap = G.Branch(HitValid->GetThenPin(),G.Math(TEXT("BooleanOR"),G.Math(TEXT("EqualEqual_ObjectObject"),Map,P(BreakHit,TEXT("HitActor"))),G.Math(TEXT("EqualEqual_ObjectObject"),Map,Owner->GetReturnValuePin())));
        auto* Distance = G.Call(UKismetMathLibrary::StaticClass(),TEXT("Vector_DistanceSquared")); Link(P(Ray,TEXT("WorldLocation")),P(Distance,TEXT("V1"))); Link(P(Groove,TEXT("OutHitLocation")),P(Distance,TEXT("V2")));
        auto* Closer = G.Branch(RoomBranch->GetThenPin(),G.Math(TEXT("Less_DoubleDouble"),Distance->GetReturnValuePin(),G.Get(TEXT("CommandMapBestDistance")))); Link(VisibleMap->GetThenPin(),Closer->GetExecPin());
        Flow = G.Set(Closer->GetThenPin(),TEXT("CommandMapFoundMap"),TEXT(""),Map); Flow = G.Set(Flow,TEXT("CommandMapFoundWorld"),TEXT(""),P(Groove,TEXT("OutHitLocation"))); G.Set(Flow,TEXT("CommandMapBestDistance"),TEXT(""),Distance->GetReturnValuePin());
        G.Return(P(Loop,TEXT("Completed")),{{TEXT("OutMap"),G.Get(TEXT("CommandMapFoundMap"))},{TEXT("OutWorldHit"),G.Get(TEXT("CommandMapFoundWorld"))},{TEXT("ReturnValue"),G.Valid(G.Get(TEXT("CommandMapFoundMap")))}});
        G.Comment(TEXT("蓝图查询鼠标沙盘：基地类型、UI遮挡、地图就绪、可见性和凹槽范围检查。指挥室使用地图自己的拾取平面；基地总览要求可见碰撞命中。"));
    }
    {
        FGraph G(BP,TEXT("CommandMap_QueryPointer")); auto* Ready = G.Call(TEXT("CommandMap_IsRoomReady"));
        auto* Guard = G.Branch(G.Exec(G.Start(),Ready),G.Both(Ready->GetReturnValuePin(),G.Both(G.Not(G.Get(TEXT("CommandMapEndingPlay"))),G.Not(G.Valid(G.Get(TEXT("CommandMapMiddleMap"))))))); G.Return(Guard->GetElsePin());
        auto* Mouse = G.Call(APlayerController::StaticClass(),TEXT("GetMousePosition")); auto* Size = G.Call(APlayerController::StaticClass(),TEXT("GetViewportSize"));
        auto* Flow = G.Exec(G.Exec(Guard->GetThenPin(),Mouse),Size);
        auto* X = P(Mouse,TEXT("LocationX")); auto* Y = P(Mouse,TEXT("LocationY"));
        auto* InBounds = G.Both(G.Both(G.Math(TEXT("GreaterEqual_DoubleDouble"),X,nullptr,TEXT("0")),G.Math(TEXT("GreaterEqual_DoubleDouble"),Y,nullptr,TEXT("0"))),G.Both(G.Math(TEXT("Less_DoubleDouble"),X,P(Size,TEXT("SizeX"))),G.Math(TEXT("Less_DoubleDouble"),Y,P(Size,TEXT("SizeY")))));
        auto* ValidMouse = G.Branch(Flow,G.Both(Mouse->GetReturnValuePin(),InBounds)); G.Return(ValidMouse->GetElsePin());
        auto* Screen = G.Call(UKismetMathLibrary::StaticClass(),TEXT("MakeVector2D")); Link(X,P(Screen,TEXT("X"))); Link(Y,P(Screen,TEXT("Y")));
        auto* FindMap = G.Call(TEXT("CommandMap_FindSandbox")); auto* Found = G.Branch(G.Exec(ValidMouse->GetThenPin(),FindMap),FindMap->GetReturnValuePin()); G.Return(Found->GetElsePin());
        auto* Resolve = G.Branch(Found->GetThenPin(),P(G.Entry,TEXT("bResolveTile")));
        auto* Tile = MapCall(G,TEXT("GetTileUnderMouse"),P(FindMap,TEXT("OutMap")));
        G.Return(G.Exec(Resolve->GetThenPin(),Tile),{{TEXT("OutMap"),P(FindMap,TEXT("OutMap"))},{TEXT("OutTile"),Tile->GetReturnValuePin()},{TEXT("OutWorldHit"),P(Tile,TEXT("OutWorldHitLocation"))},{TEXT("OutScreenPosition"),Screen->GetReturnValuePin()}},{{TEXT("ReturnValue"),TEXT("true")}});
        G.Return(Resolve->GetElsePin(),{{TEXT("OutMap"),P(FindMap,TEXT("OutMap"))},{TEXT("OutWorldHit"),P(FindMap,TEXT("OutWorldHit"))},{TEXT("OutScreenPosition"),Screen->GetReturnValuePin()}},{{TEXT("ReturnValue"),TEXT("true")}});
    }
    {
        FGraph G(BP,TEXT("CommandMap_EndMiddle")); auto* Guard = G.Branch(G.Start(),G.Valid(G.Get(TEXT("CommandMapMiddleMap"))));
        auto* Flow = G.Exec(Guard->GetThenPin(),MapCall(G,TEXT("EndDragMap"),G.Get(TEXT("CommandMapMiddleMap"))));
        Flow = G.Exec(Flow,MapCall(G,TEXT("ConsumeTileClickSuppressionAfterDrag"),G.Get(TEXT("CommandMapMiddleMap"))));
        G.Set(Flow,TEXT("CommandMapMiddleMap"),TEXT("None")); G.Set(Guard->GetElsePin(),TEXT("CommandMapMiddleMap"),TEXT("None"));
    }
    {
        FGraph G(BP,TEXT("CommandMap_CancelAll")); auto* Flow = G.Invoke(G.Start(),TEXT("CommandMap_CancelPointer")); Flow = G.Invoke(Flow,TEXT("CommandMap_EndMiddle"));
        auto* Camera = G.Call(UGameMainMapLibrary::StaticClass(),TEXT("GetGameMainMapPlayerCamera")); auto* Guard = G.Branch(Flow,G.Valid(Camera->GetReturnValuePin()));
        auto* Stop = G.Call(AFCS_FreeCameraPawn::StaticClass(),TEXT("TriggerMouseRotate")); Link(Camera->GetReturnValuePin(),P(Stop,TEXT("self"))); D(Stop,TEXT("bEnable"),TEXT("false")); G.Exec(Guard->GetThenPin(),Stop);
        G.Comment(TEXT("所有沙盘取消逻辑都在本蓝图：结束插件拖拽、消费遗留点击抑制、清空左右中键状态。通用输入重置事件仅通知此处。"));
    }
    {
        FGraph G(BP,TEXT("CommandMap_SetRoomInput")); auto* Flow = G.Invoke(G.Start(),TEXT("CommandMap_CancelAll")); auto* Enabled = G.Branch(Flow,P(G.Entry,TEXT("Enabled")));
        auto* First = G.Branch(Enabled->GetThenPin(),G.Not(G.Get(TEXT("CommandMapRoomInputEnabled"))));
        Flow = G.Set(First->GetThenPin(),TEXT("CommandMapPreviousClickEvents"),TEXT(""),G.Get(TEXT("bEnableClickEvents")));
        Flow = G.Set(Flow,TEXT("CommandMapRoomInputEnabled"),TEXT("true")); G.Set(Flow,TEXT("bEnableClickEvents"),TEXT("false"));
        auto* WasEnabled = G.Branch(Enabled->GetElsePin(),G.Get(TEXT("CommandMapRoomInputEnabled")));
        Flow = G.Set(WasEnabled->GetThenPin(),TEXT("bEnableClickEvents"),TEXT(""),G.Get(TEXT("CommandMapPreviousClickEvents"))); G.Set(Flow,TEXT("CommandMapRoomInputEnabled"),TEXT("false"));
        G.Comment(TEXT("指挥室通过蓝图临时关闭Actor原生点击事件，选择仅由左键抬起判断。离开恢复原始开关，避免双重选择。"));
    }
    {
        FGraph G(BP,TEXT("CommandMap_BeginMiddle")); auto* Busy = G.Branch(G.Start(),G.Get(TEXT("bCommandMapPointerPending"))); G.Return(Busy->GetThenPin(),{},{{TEXT("ReturnValue"),TEXT("true")}});
        auto* Query = G.Call(TEXT("CommandMap_FindSandbox")); auto* Found = G.Branch(G.Exec(Busy->GetElsePin(),Query),Query->GetReturnValuePin());
        auto* Begin = MapCall(G,TEXT("BeginDragMapWithMouse"),P(Query,TEXT("OutMap"))); auto* Begun = G.Branch(G.Exec(Found->GetThenPin(),Begin),Begin->GetReturnValuePin());
        G.Return(G.Set(Begun->GetThenPin(),TEXT("CommandMapMiddleMap"),TEXT(""),P(Query,TEXT("OutMap"))),{},{{TEXT("ReturnValue"),TEXT("true")}});
        G.Return(Begun->GetElsePin(),{},{{TEXT("ReturnValue"),TEXT("true")}});
        auto* Panel = G.Call(TEXT("CommandMap_OverPanel")); auto* Room = G.Call(TEXT("CommandMap_IsInRoom"));
        auto* Flow = G.Exec(G.Exec(Found->GetElsePin(),Panel),Room);
        G.Return(Flow,{{TEXT("ReturnValue"),G.Math(TEXT("BooleanOR"),Panel->GetReturnValuePin(),Room->GetReturnValuePin())}});
    }
    {
        FGraph G(BP,TEXT("CommandMap_Tick")); auto* Seq = G.Sequence(G.Start()); G.Invoke(Seq->GetThenPinGivenIndex(0),TEXT("CommandMap_UpdatePointer"));
        auto* Guard = G.Branch(Seq->GetThenPinGivenIndex(1),G.Valid(G.Get(TEXT("CommandMapMiddleMap"))));
        auto* Query = G.Call(TEXT("CommandMap_FindSandbox")); auto* Same = G.Branch(G.Exec(Guard->GetThenPin(),Query),G.Both(Query->GetReturnValuePin(),G.Math(TEXT("EqualEqual_ObjectObject"),P(Query,TEXT("OutMap")),G.Get(TEXT("CommandMapMiddleMap")))));
        G.Exec(Same->GetThenPin(),MapCall(G,TEXT("DragMapToMousePosition"),G.Get(TEXT("CommandMapMiddleMap")))); G.Invoke(Same->GetElsePin(),TEXT("CommandMap_EndMiddle"));
    }
    {
        FGraph G(BP,TEXT("CommandMap_Zoom")); auto* Guard = G.Branch(G.Start(),G.Not(G.Get(TEXT("bCommandMapPointerPending"))));
        auto* Query = G.Call(TEXT("CommandMap_FindSandbox")); auto* Found = G.Branch(G.Exec(Guard->GetThenPin(),Query),Query->GetReturnValuePin());
        auto* Zoom = MapCall(G,TEXT("AddZoomAtWorldLocation"),P(Query,TEXT("OutMap"))); Link(P(Query,TEXT("OutWorldHit")),P(Zoom,TEXT("WorldPivotLocation"))); Link(P(G.Entry,TEXT("Delta")),P(Zoom,TEXT("ZoomDelta"))); G.Exec(Found->GetThenPin(),Zoom);
        auto* Panel = G.Call(TEXT("CommandMap_OverPanel")); auto* Room = G.Call(TEXT("CommandMap_IsInRoom")); auto* Flow = G.Exec(G.Exec(Found->GetElsePin(),Panel),Room);
        auto* Outside = G.Branch(Flow,G.Not(G.Math(TEXT("BooleanOR"),Panel->GetReturnValuePin(),Room->GetReturnValuePin())));
        auto* Camera = G.Call(UGameMainMapLibrary::StaticClass(),TEXT("GetGameMainMapPlayerCamera")); auto* ValidCamera = G.Branch(Outside->GetThenPin(),G.Valid(Camera->GetReturnValuePin()));
        auto* CameraZoom = G.Call(AFCS_FreeCameraPawn::StaticClass(),TEXT("ZoomCamera")); Link(Camera->GetReturnValuePin(),P(CameraZoom,TEXT("self"))); Link(P(G.Entry,TEXT("Delta")),P(CameraZoom,TEXT("Value"))); G.Exec(ValidCamera->GetThenPin(),CameraZoom);
    }
    // Remove only the old common-context activation chain. Parent C++ now owns its lifetime.
    if (auto* Main = Find(BP,TEXT("EventGraph")))
    {
        const TSet<FName> Remove = {TEXT("K2Node_Self_0"),TEXT("K2Node_GetSubsystemFromPC_0"),TEXT("K2Node_VariableGet_0"),TEXT("K2Node_CallFunction_0"),TEXT("K2Node_CallFunction_1"),TEXT("K2Node_IfThenElse_0"),TEXT("K2Node_ExecutionSequence_0")};
        const auto Nodes = Main->Nodes;
        for (UEdGraphNode* N : Nodes)
        {
            if (Remove.Contains(N->GetFName())) { N->BreakAllNodeLinks(); Main->RemoveNode(N); }
            if (N->IsA<UEdGraphNode_Comment>() && N->NodeComment.Contains(TEXT("激活通用映射"))) N->NodeComment = TEXT("通用/基地/战斗映射由父类C++按GameState地图类型管理。鼠标行为在 MouseEventGraph 中编辑。");
        }
        FGraph G(BP,Main);
        auto* Tick = Event(G,TEXT("ReceiveTick"),AActor::StaticClass()); Tick->SetEnabledState(ENodeEnabledState::Enabled);
        auto* Update = G.Call(TEXT("CommandMap_Tick")); Append(G,P(Tick,TEXT("then")),P(Update,TEXT("execute")));
        auto* Reset = Event(G,TEXT("OnInputStateReset"),AGameMainMapPlayerController::StaticClass()); G.Invoke(P(Reset,TEXT("then")),TEXT("CommandMap_CancelAll"));
        auto* End = Event(G,TEXT("ReceiveEndPlay"),AActor::StaticClass()); auto* Cancel = G.Call(TEXT("CommandMap_CancelAll")); Append(G,P(End,TEXT("then")),P(Cancel,TEXT("execute")));
        G.Set(P(Cancel,TEXT("then")),TEXT("CommandMapEndingPlay"),TEXT("true"));
    }
    {
        auto* Mouse = Find(BP,TEXT("MouseEventGraph")); check(Mouse); FGraph G(BP,Mouse);
        UK2Node_EnhancedInputAction* Left = nullptr; UK2Node_EnhancedInputAction* Middle = nullptr;
        for (UEdGraphNode* N : Mouse->Nodes) if (auto* Action = Cast<UK2Node_EnhancedInputAction>(N))
        { if (Action->InputAction->GetName() == TEXT("IA_MouseLeft")) Left = Action; if (Action->InputAction->GetName() == TEXT("IA_MouseMiddle")) Middle = Action; }
        check(Left && Middle);
        G.Invoke(P(Left,TEXT("Started")),TEXT("CommandMap_BeginPointer")); G.Invoke(P(Left,TEXT("Completed")),TEXT("CommandMap_ReleasePointer")); G.Invoke(P(Left,TEXT("Canceled")),TEXT("CommandMap_CancelPointer"));
        const auto Fallback = P(Middle,TEXT("Started"))->LinkedTo; P(Middle,TEXT("Started"))->BreakAllPinLinks();
        auto* StartMiddle = G.Call(TEXT("CommandMap_BeginMiddle")); auto* Handled = G.Branch(G.Exec(P(Middle,TEXT("Started")),StartMiddle),StartMiddle->GetReturnValuePin());
        for (auto* Pin : Fallback) Link(Handled->GetElsePin(),Pin);
        for (FName Name : {FName(TEXT("Completed")),FName(TEXT("Canceled"))})
        { auto* End = G.Call(TEXT("CommandMap_EndMiddle")); Append(G,P(Middle,Name),P(End,TEXT("execute"))); }
        auto* WheelEvent = G.Node<UK2Node_EnhancedInputAction>([&](auto* N) { N->InputAction = Wheel; });
        auto* Zoom = G.Call(TEXT("CommandMap_Zoom")); Link(P(WheelEvent,TEXT("ActionValue")),P(Zoom,TEXT("Delta"))); G.Exec(P(WheelEvent,TEXT("Triggered")),Zoom);
        G.Comment(TEXT("Enhanced Input → 本蓝图函数。左键按下记录，抬起才选中；超过阈值拖拽。中键优先沙盘拖动，其他位置沿用原相机旋转。基地滚轮优先缩放沙盘，其他位置缩放相机。"));
    }
    auto* Defaults = CastChecked<AGameMainMapPlayerController>(BP->GeneratedClass->GetDefaultObject());
    if (!Defaults->CommonInputMappingContext) Defaults->CommonInputMappingContext = LoadObject<UInputMappingContext>(nullptr,TEXT("/Game/System/Input/Common/IMC_Common"));
    if (!Defaults->BaseInputMappingContext) Defaults->BaseInputMappingContext = LoadObject<UInputMappingContext>(nullptr,TEXT("/Game/System/Input/Base/IMC_Base"));
    if (!Defaults->BattleInputMappingContext) Defaults->BattleInputMappingContext = LoadObject<UInputMappingContext>(nullptr,TEXT("/Game/System/Input/Battle/IMC_Battle"));
    return Compile(BP);
}
}
