import unreal,runpy
from pathlib import Path
ROOT=Path('S:/UE_WorkSpace/SilverChoir')
aa=unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
b=next(a for a in aa.get_all_level_actors() if isinstance(a,unreal.BaseSandboxMap))
unreal.SystemLibrary.execute_console_command(b.get_world(),'r.CustomDepth 3')
helper=runpy.run_path(str(ROOT/'Scripts/Editor/base_sandbox_materials.py'))
m=unreal.load_asset('/Game/System/Map/BaseMap/Sandbox/Materials/M_BaseSandboxGrid')
helper['_validate_owned'](m,'grid')
helper['_build_grid'](m)
unreal.MaterialEditingLibrary.recompile_material(m)
assets=unreal.get_editor_subsystem(unreal.EditorAssetSubsystem)
assert assets.save_loaded_asset(m)
cfg=b.get_editor_property('map_config')
cfg.set_editor_property('use_custom_stencil_for_map_decals',True)
assert assets.save_loaded_asset(cfg)
b.rebuild_map_from_config()
for t in b.get_editor_property('spawned_tiles'):t.set_folder_path('BaseSandbox/Tiles')
assert unreal.get_editor_subsystem(unreal.LevelEditorSubsystem).save_current_level()
