IMPLEMENT_SIMPLE_AUTOMATION_TEST(FEHBCutPartitionWriteTest,"EHBValidation.Persistence.WriteCutPartition",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FEHBCutPartitionWriteTest::RunTest(const FString& Parameters)
{
 FString Map,Path;if(!PersistencePaths(Map,Path,TEXT("CutPartition"))||FPackageName::DoesPackageExist(Map)||FPaths::FileExists(Path))return false;
 auto* World=UEditorLoadingAndSavingUtils::NewBlankMap(false);auto* B=World->SpawnActor<AEHB_Building>();auto* S=World->SpawnActor<AEHB_FloorSlab>();if(!B||!S)return false;S->AttachToBuilding(B,FTransform(FRotator(0,37,0),FVector(100,200,300)));S->FloorIndex=1;S->RoomFillFloorIndex=1;S->VisualExpansion=0;
 const TArray<FVector> Outer={{0,0,0},{500,0,0},{500,500,0},{0,500,0}};TArray<FEHBFloorSlabHole> Holes;Holes.AddDefaulted_GetRef().LocalPolygon={{300,100,0},{350,100,0},{350,150,0},{300,150,0}};
 FEHBCutOperation Cut;for(const auto& P:TArray<FVector>{{200,-100,0},{220,-100,0},{220,600,0},{200,600,0}})Cut.Source.ExplicitPolygon.Points.AddDefaulted_GetRef().LocalPosition=P;Cut.EnsureGuids();
 FEHBSlabDisplayPartition Partition;FName Status;if(!S->BuildCandidateDisplayRegions(Outer,Holes,{Cut},Partition.Regions,Status))return false;S->CaptureDisplayPartitionSource(Outer,Holes,{Cut},Partition);
 if(!S->ValidatePartitionedSlabState(Outer,Holes,{Cut},Partition)||!S->SetPartitionedSlabState(Outer,Holes,{Cut},Partition))return false;S->RecordOutlineSource(EEHBOutlineSource::RetainedRegion);
 auto Data=MakeShared<FJsonObject>();Data->SetStringField(TEXT("schema"),TEXT("EHB.CutPartition.v1"));Data->SetStringField(TEXT("element"),S->ElementGuid.ToString());Data->SetStringField(TEXT("surface"),S->FindLogicalSurfaceIdentity(TEXT("Slab.Surface")).ToString());FString State;FJsonObjectConverter::UStructToJsonObjectString(S->DisplayPartition,State);Data->SetStringField(TEXT("partition"),State);
 if(!UEditorLoadingAndSavingUtils::SaveMap(World,Map))return false;FString Json;FJsonSerializer::Serialize(Data,TJsonWriterFactory<>::Create(&Json));return FFileHelper::SaveStringToFile(Json,*Path);
}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FEHBCutPartitionReadTest,"EHBValidation.Persistence.ReadCutPartition",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FEHBCutPartitionReadTest::RunTest(const FString& Parameters)
{
 FString Map,Path,Json;if(!PersistencePaths(Map,Path,TEXT("CutPartition"))||!FFileHelper::LoadFileToString(Json,*Path))return false;TSharedPtr<FJsonObject> Data;if(!FJsonSerializer::Deserialize(TJsonReaderFactory<>::Create(Json),Data)||Data->GetStringField(TEXT("schema"))!=TEXT("EHB.CutPartition.v1"))return false;
 auto* World=GEditor->GetEditorWorldContext().World();FGuid Id;FGuid::Parse(Data->GetStringField(TEXT("element")),Id);AEHB_FloorSlab* S=nullptr;for(TActorIterator<AEHB_FloorSlab> It(World);It;++It)if(It->ElementGuid==Id)S=*It;if(!S||S->CutOperations.Num()!=1||S->LocalHoles.Num()!=1)return false;
 TestEqual(TEXT("Correct saved map"),World->GetOutermost()->GetName(),Map);FString State;FJsonObjectConverter::UStructToJsonObjectString(S->DisplayPartition,State);TestEqual(TEXT("Exact complete partition snapshot"),State,CanonicalDisplayPartitionManifest(*this,Data->GetStringField(TEXT("partition"))));TestEqual(TEXT("Stable surface port"),S->FindLogicalSurfaceIdentity(TEXT("Slab.Surface")).ToString(),Data->GetStringField(TEXT("surface")));TestTrue(TEXT("Cold versioned provenance"),S->IsRecordedOutlineUnchanged());
 if(!TestTrue(TEXT("Cold source matches partition"),S->RebuildSlabMesh()))return false;TestTrue(TEXT("Cold actual top area"),FMath::Abs(CutSlabTopArea(S)-237500)<0.01);
 auto Changed=S->CutOperations;Changed[0].Source.Height+=1;TestFalse(TEXT("Cold stale preflight rejected"),S->ValidatePartitionedSlabState(S->LocalTopPolygon,S->LocalHoles,Changed,S->DisplayPartition));TestFalse(TEXT("Cold stale apply rejected"),S->SetPartitionedSlabState(S->LocalTopPolygon,S->LocalHoles,Changed,S->DisplayPartition));TestEqual(TEXT("Failed apply preserved source"),S->CutOperations[0].Source.Height,Changed[0].Source.Height-1);
 for(auto& P:Changed[0].Source.ExplicitPolygon.Points)P.LocalPosition.X+=30;auto Next=S->DisplayPartition;FName Status;if(!S->BuildCandidateDisplayRegions(S->LocalTopPolygon,S->LocalHoles,Changed,Next.Regions,Status))return false;S->CaptureDisplayPartitionSource(S->LocalTopPolygon,S->LocalHoles,Changed,Next);
 {FScopedTransaction Transaction(FText::FromString(TEXT("Cold partition replan")));if(!S->SetPartitionedSlabState(S->LocalTopPolygon,S->LocalHoles,Changed,Next))return false;}
 GEditor->UndoTransaction();FJsonObjectConverter::UStructToJsonObjectString(S->DisplayPartition,State);TestEqual(TEXT("Cold undo complete snapshot"),State,CanonicalDisplayPartitionManifest(*this,Data->GetStringField(TEXT("partition"))));TestTrue(TEXT("Cold undo rebuild"),S->RebuildSlabMesh());GEditor->RedoTransaction();TestTrue(TEXT("Cold redo rebuild"),S->RebuildSlabMesh());TestEqual(TEXT("Cold redo source"),S->CutOperations[0].Source.Height,Changed[0].Source.Height);return true;
}
