#include "Actors/EHB_Wall.h"
#include "Actors/EHB_Pillar.h"
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FEHBLogicalWallActorTest,"EHB.Surfaces.LogicalWallActor",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FEHBLogicalWallActorTest::RunTest(const FString& Parameters)
{
 auto* World=GEditor->GetEditorWorldContext().World();auto* B=World->SpawnActor<AEHB_Building>();AEHB_Wall* Wall=nullptr;auto* A=World->SpawnActor<AEHB_Pillar>();auto* C=World->SpawnActor<AEHB_Pillar>();ON_SCOPE_EXIT{if(Wall)Wall->Destroy();A->Destroy();C->Destroy();B->Destroy();};
 B->SetActorTransform(FTransform(FRotator(0,37,0),FVector(900,-600,40)));const FVector Start(0,0,300),End(500,0,300);
 A->AttachToBuilding(B,FTransform::Identity);C->AttachToBuilding(B,FTransform::Identity);A->ConfigureAsPolygonPillar(260,80,60,FTransform(FRotator(0,25,0),Start));C->ConfigureAsPolygonPillar(260,60,40,FTransform(FRotator(0,-12,0),End));Wall=B->ConnectPillars(A,C,260,24);if(!TestNotNull(TEXT("Real pillar connection creates wall"),Wall))return false;
 TArray<FEHBLogicalSurfaceDefinition> Surfaces;FName Status;if(!TestTrue(*Status.ToString(),Wall->QueryLogicalBaseSurfaces(Surfaces,Status)))return false;TestEqual(TEXT("Both semantic sides"),Surfaces.Num(),2);if(Surfaces.Num()!=2)return false;
 auto MeshArea=[](const UEHBGeneratedMeshComponent* Mesh){double Area=0;for(int32 Section=0;Section<Mesh->GetNumSections();++Section)if(const auto* Part=Mesh->GetProcMeshSection(Section))for(int32 I=0;I<Part->ProcIndexBuffer.Num();I+=3){const auto P=Part->ProcVertexBuffer[Part->ProcIndexBuffer[I]].Position,Q=Part->ProcVertexBuffer[Part->ProcIndexBuffer[I+1]].Position,R=Part->ProcVertexBuffer[Part->ProcIndexBuffer[I+2]].Position;Area+=FVector::CrossProduct(Q-P,R-P).Size()*0.5;}return Area;};
 const auto WallTransform=Wall->GetElementLocalTransform();
 for(int32 I=0;I<2;++I)
 {
  const auto& S=Surfaces[I];const bool Left=I==0;TestEqual(TEXT("Stable side port"),S.SurfaceGuid,Wall->FindLogicalSurfaceIdentity(Left?TEXT("Wall.Left"):TEXT("Wall.Right")));TestTrue(TEXT("Side area includes endpoint trims"),S.GetAreaCm2()<500*260);TestTrue(TEXT("Logical base matches actual uncut mesh area"),FMath::Abs(S.GetAreaCm2()-MeshArea(Left?Wall->LeftWallMeshComponent.Get():Wall->RightWallMeshComponent.Get()))<0.05);TestTrue(TEXT("Outward side normal"),FVector::DotProduct(S.PlaneToBuilding.GetUnitAxis(EAxis::Z),WallTransform.GetUnitAxis(EAxis::Y)*(Left?1:-1))>0.999999);TestFalse(TEXT("Vertical side cannot claim horizontal support"),S.bCanSupport);TestEqual(TEXT("Centimeter thickness"),S.Thickness,24.0);
  const FVector2D Point(20,30);FVector2D Projected;double Distance;TestTrue(TEXT("Wall chart projection"),S.Project(S.ToBuilding(Point)+S.PlaneToBuilding.GetUnitAxis(EAxis::Z)*7,Projected,Distance)&&Projected.Equals(Point,1.e-6)&&FMath::IsNearlyEqual(Distance,7.0,1.e-6));
 }
 TestTrue(TEXT("Pillar attached before movement"),A->GetAttachParentActor()==B);TestTrue(TEXT("Wall source matches pillar ID"),Wall->StartPillarGuid==A->ElementGuid);const double OldArea=Surfaces[0].GetAreaCm2();A->SetElementLocalTransform(FTransform(FRotator(0,25,0),Start+FVector(20,0,0)));A->RebuildPillarMesh();TestTrue(TEXT("Requested pillar location applied"),A->GetElementLocalTransform().GetLocation().Equals(Start+FVector(20,0,0),0.01));Wall->RefreshFromConnectedPillars();if(!TestTrue(TEXT("Changed pillar source remains queryable"),Wall->QueryLogicalBaseSurfaces(Surfaces,Status))||Surfaces.Num()!=2)return false;AddInfo(FString::Printf(TEXT("Wall fixture authority=%d oldArea=%.3f newArea=%.3f start=%s end=%s pillarWidth=%.1f"),B->WallNodeAuthority.Version,OldArea,Surfaces[0].GetAreaCm2(),*Wall->LocalStart.ToString(),*Wall->LocalEnd.ToString(),A->Width));TestTrue(TEXT("Pillar movement updates logical side trim"),FMath::Abs(Surfaces[0].GetAreaCm2()-OldArea)>0.1);
 const auto Before=Surfaces;FEHBWallDoorWindowConnection Connection;Connection.DoorWindowGuid=FGuid::NewGuid();Connection.OpeningWidth=40;Connection.OpeningHeight=50;Connection.BottomHeight=50;Connection.DistanceFromStart=(Wall->LocalEnd-Wall->LocalStart).Size2D()*0.5;Wall->DoorWindowConnections.Add(Connection);Wall->RebuildWallMesh();AddInfo(FString::Printf(TEXT("Wall cut count=%d baseArea=%.3f meshArea=%.3f height=%.1f frame=%s"),Wall->CutOperations.Num(),Before[0].GetAreaCm2(),MeshArea(Wall->LeftWallMeshComponent),Wall->Height,*Wall->GetElementLocalTransform().ToString()));TestTrue(TEXT("Opening reduces real wall mesh"),MeshArea(Wall->LeftWallMeshComponent)<Before[0].GetAreaCm2()-100);
 TestTrue(TEXT("Logical base excludes external opening operation"),Wall->QueryLogicalBaseSurfaces(Surfaces,Status));if(Surfaces.Num()!=2)return false;TestEqual(TEXT("Base side area unchanged by opening"),Surfaces[0].GetAreaCm2(),Before[0].GetAreaCm2());
 const auto Identities=Wall->LogicalSurfaceIdentities;TArray<UEHBGeneratedMeshComponent*> Meshes;Wall->GetGeneratedMeshComponents(Meshes);for(auto* Mesh:Meshes)Mesh->DestroyComponent();Wall->LeftWallMeshComponent=nullptr;Wall->RightWallMeshComponent=nullptr;
 TestTrue(TEXT("Wall query works without generated components"),Wall->QueryLogicalBaseSurfaces(Surfaces,Status));if(Surfaces.Num()!=2)return false;for(int32 I=0;I<2;++I){TestEqual(TEXT("Renderer-free ID"),Surfaces[I].SurfaceGuid,Before[I].SurfaceGuid);TestEqual(TEXT("Renderer-free trimmed area"),Surfaces[I].GetAreaCm2(),Before[I].GetAreaCm2());}TestEqual(TEXT("Query never registers new identities"),Wall->LogicalSurfaceIdentities.Num(),Identities.Num());
 Wall->CurveControlOffset=60;TestFalse(TEXT("Curved source never flattened into one plane"),Wall->QueryLogicalBaseSurfaces(Surfaces,Status));TestEqual(TEXT("Explicit curved definition requirement"),Status,FName(TEXT("CurvedLogicalSurfaceRequiresDefinition")));TestTrue(TEXT("Failed query clears partial output"),Surfaces.IsEmpty());Wall->CurveControlOffset=0;Wall->Thickness=0;TestFalse(TEXT("Invalid author thickness rejected"),Wall->QueryLogicalBaseSurfaces(Surfaces,Status));Wall->Thickness=24;
 Wall->SetActorScale3D(FVector(2,1,1));TestFalse(TEXT("No hidden scale in logical wall plane"),Wall->QueryLogicalBaseSurfaces(Surfaces,Status));Wall->SetActorScale3D(FVector::OneVector);
 return true;
}
